/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Day27Problem.EmployeePayroll;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
